### ISSUE TITLE
[BUG]: Same Key ID for different ranges in ref VCF

### ISSUE THREAD

**Issue by jsarriaa** [maize-genetics/phg_v2#258] opened 2024-11-25 13:52 UTC
### Description

I am not sure if this is actually intended to be like this or I am missunderstanding anything, but working with the reference h.vcf we realize about this:

`zcat vcf_dbs/hvcf_files/MorexV3.h.vcf.gz | grep "8fac2e68e88ec743edbc450f11511350"`

```
##ALT=<ID=8fac2e68e88ec743edbc450f11511350,Description="haplotype data for line: MorexV3",Source="data/prepared_assemblies/MorexV3.fa",SampleName=MorexV3,Regions=chr1H:412645595-412651134,Checksum=8fac2e68e88ec743edbc450f11511350,RefChecksum=8fac2e68e88ec743edbc450f11511350,RefRange=chr1H:412645595-412651134>

chr1H   412645595       .       C       <8fac2e68e88ec743edbc450f11511350>      .       .       END=412651134   GT:AD:DP        1:0,2,0:2
chr1H   412659123       .       C       <8fac2e68e88ec743edbc450f11511350>      .       .       END=412664662   GT:AD:DP        1:0,2,0:2
```

There is a single metadata line for this key, so when afterwards we are looking for anything in our graph we are ending only in this line, when apparently there are two different regions. May it be because there are identical, and the graph is collapsing the ranges in a single one? I was not expecting this in the reference h.vcf.
To provide some context, we are working with a couple of annotated pangenes which are described in these two ranges separately (but apparently are almost identical), and we are now trying to understand what is actually going on here.

In fact, there should be more keys like this one that we just faced by chance. Doing a quick check, we realized:

```
zcat PHG_panbarleyV1/vcf_dbs/hvcf_files/MorexV3.h.vcf.gz | grep "^##ALT" | wc -l
66597
zcat PHG_panbarleyV1/vcf_dbs/hvcf_files/MorexV3.h.vcf.gz | grep "^chr" | wc -l
66204
```

version to build the ref hvcf: 2.4.21.176 (maybe this issue has been reviwed later, sorry if it is the case)

We do appreciate any help or advice. If any other data about our database is needed, please ask!

Joan

### Expected behavior

Should not provide a different key for each range at the reference haplotype file?

### PHG version

2.4.21.176

**Comment by lynnjo** [comment] 2024-11-25 14:54
@jsarriaa  How many refranges are in your bed file?  I would expect to see a data entry in the h.vcf file for each reference range.  When creating the h.vcf files for the non-reference samples there could be missing entries if nothing aligned at that region.  But for the reference range, the h.vcf file is created by splitting the sequence based on the entries in the bed file, so none should be skipped.   I'll take another look at the code.

The ALT header ID across multiple files can be the same when the sequence is identical (i.e. checksum is the same). So when the files are merged by HaplotypeGraph the last entry into the ALT Header map is what is recorded.  But this doesn't appear to be your concern above.

**Comment by lynnjo** [comment] 2024-11-25 15:04
I misread your numbers above.  You have more data lines than ALT header lines, and that is correct.  Because the "ID" of the alt header must be unique there is only one instance of that ID recorded and it will be the first one.  If different ranges of the genome have identical sequence then yes, only the first one is represented in the alt header lines.

So the code is working as designed, but we'll discuss and I'll get back to you.

**Comment by jsarriaa** [comment] 2024-11-25 15:35
Yes, you are right. There are as many range keys for genes annotated at the ensambled chromosomes, and none of them is skipped at the reference h.vcf

```
cat ../PHG_panbarleyV1/data/ref_ranges.bed | wc -l
67553
cat ../PHG_panbarleyV1/data/ref_ranges.bed | grep "^CAJ" | wc -l
1349
cat ../PHG_panbarleyV1/data/ref_ranges.bed | grep "^chr" | wc -l
66204
```

Number of keys in the h.vcf file matches with all refranges inside a chromosome. If I am not wrong, we expect to those that are not in pseudochromosomes (in our case are annotated starting with CAJ) to be retained at any other genome in which it is actually aligned inside a chr. 

So I was wrong about my thoughts :) I hope  any other user finds this discussion useful. Thanks for the answer!

**Comment by lynnjo** [comment] 2024-11-25 15:50
Are you ok with how this is setup then?  May I close this issue?

**Closed** 2024-11-25 19:05 UTC
Labels: bug
